export const items = [
    "All",
    'Amazon Devices',
    'Amazon Fashion',
    'Amazon Fresh',
    'Amazon Pharmacy',
    'Appliances',
    'Apps & Games',
    'Beauty',
    'Books',
    'Car & Motorbike',
    'Clothing & Accessories',
    'Collectibles',
    'Computers & Accessories',
    'Deals',
    'Electronics',
    'Furniture',
    'Garden & Outdoors',
    'Gift Cards',
    'Grocery & Gourmet Foods',
    'Health & Personal Care',
    'Home & Kitchen',
    'Industrial & Scientific',
    'Jewellery',
    'Kindle Store',
    'Luggage & Bags',
    'Luxury Beauty',
];